name: Generate pacman animation

on:
  schedule:
    - cron: "0 */12 * * *"   # every 12 hours (run at minute 0)
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: generate pacman-contribution-graph.svg
        uses: abozanona/pacman-contribution-graph@main
        with:
          # provide your username as a plain string
          github_user_name: "LuizaBorges23"
          # if the action has other options (output folder), add them here
        # If this action needs node, steps to setup node/npm can be added before this

      - name: Ensure dist exists
        run: |
          mkdir -p dist
          # If the pacman action generated files elsewhere, move them here, for example:
          # mv pacman-contribution-graph.svg dist/ || true
          ls -la dist

      - name: push pacman-contribution-graph.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
